"""Job store for delegated Codex tasks.

Jobs are JSON files on disk, one per task, written atomically. Workers run
detached, so state must survive the MCP server restarting or the worker being
killed. Rather than trusting the worker to always write a terminal record, reads
reconcile: a job marked `running` whose worker PID is gone is resolved to a
terminal state at read time. That covers worker crashes, kill -9, and reboots.
"""

import json
import os
import re
import secrets
import signal
import subprocess
import time
from pathlib import Path

from config import Config

TERMINAL_STATUSES = {"completed", "failed", "cancelled", "timeout"}
ACTIVE_STATUSES = {"queued", "running"}

# Job ids are generated by new_job_id; anything else is not a job id. Validating
# the shape keeps a caller-supplied reference from walking out of the jobs dir
# via ".." or an absolute path and pointing job_path() at an arbitrary file.
_JOB_ID_RE = re.compile(r"^[a-z_]+-[0-9a-z]+-[0-9a-f]{6}$")

# A queued job whose worker never published a pid this long after creation is
# assumed to have failed at launch. Without this it would sit queued forever:
# reconcile leaves pid-less queued records alone, and prune spares active jobs.
_LAUNCH_GRACE_SECONDS = 120


def jobs_dir() -> Path:
    path = Path(Config.STATE_DIR) / "jobs"
    path.mkdir(parents=True, exist_ok=True)
    return path


def new_job_id(prefix: str = "task") -> str:
    """Time-ordered, collision-resistant id: task-<base36 ms>-<rand6>."""
    stamp = int(time.time() * 1000)
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    encoded = ""
    while stamp:
        stamp, rem = divmod(stamp, 36)
        encoded = digits[rem] + encoded
    return f"{prefix}-{encoded}-{secrets.token_hex(3)}"


def is_valid_job_id(job_id: str) -> bool:
    return bool(_JOB_ID_RE.match(job_id or ""))


def job_path(job_id: str) -> Path:
    if not is_valid_job_id(job_id):
        raise ValueError(f"Not a valid job id: {job_id!r}")
    return jobs_dir() / f"{job_id}.json"


def output_path(job_id: str) -> Path:
    return jobs_dir() / f"{job_id}.out"


def log_path(job_id: str) -> Path:
    return jobs_dir() / f"{job_id}.log"


def schema_path(job_id: str) -> Path:
    return jobs_dir() / f"{job_id}.schema.json"


def prompt_path(job_id: str) -> Path:
    return jobs_dir() / f"{job_id}.prompt.txt"


def stderr_path(job_id: str) -> Path:
    return jobs_dir() / f"{job_id}.stderr.txt"


def sidecar_paths(job_id: str) -> tuple[Path, ...]:
    """Every file a job creates. Pruning must cover all of them — the prompt
    can carry proprietary context, and unlisted files outlive CODEX_MAX_JOBS.
    """
    return (
        job_path(job_id),
        output_path(job_id),
        log_path(job_id),
        schema_path(job_id),
        cancel_path(job_id),
        prompt_path(job_id),
        stderr_path(job_id),
    )


def cancel_path(job_id: str) -> Path:
    return jobs_dir() / f"{job_id}.cancel"


def request_cancel(job_id: str) -> None:
    """Mark a job cancelled using a sentinel file.

    Deliberately not just a field on the record. The worker rewrites the record
    on every phase change via read-modify-write, so a `cancel_requested` field
    set concurrently can be read-then-clobbered — after which the job reports
    "failed: worker exited without recording a result" instead of "cancelled".
    A separate file cannot be lost that way. The field is still set for
    visibility, but this file is what the code trusts.
    """
    cancel_path(job_id).touch()
    update_job(job_id, cancel_requested=True)


def is_cancel_requested(job_id: str) -> bool:
    return cancel_path(job_id).exists()


def write_job(record: dict) -> dict:
    """Write a job record atomically (temp file + rename)."""
    path = job_path(record["id"])
    tmp = path.with_suffix(f".{os.getpid()}.tmp")
    tmp.write_text(json.dumps(record, indent=2))
    os.replace(tmp, path)
    return record


def update_job(job_id: str, **fields) -> dict | None:
    """Read-modify-write a job record. Returns the updated record."""
    record = read_job(job_id, reconcile_state=False)
    if record is None:
        return None
    record.update(fields)
    return write_job(record)


def append_log(job_id: str, message: str) -> None:
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    with open(log_path(job_id), "a") as handle:
        handle.write(f"[{stamp}] {message}\n")


def read_log(job_id: str, tail_lines: int = 40) -> list[str]:
    path = log_path(job_id)
    if not path.exists():
        return []
    lines = path.read_text().splitlines()
    return lines[-tail_lines:]


def _is_our_worker(pid: int) -> bool:
    """Check the pid actually belongs to one of our workers.

    PIDs are reused. After a reboot or a long gap, a recorded worker_pid can
    belong to something else entirely — which would make a dead job look alive
    forever, and (far worse) make terminate_tree signal an unrelated process
    group. Matching the command line makes both failures impossible.
    """
    try:
        result = subprocess.run(
            ["ps", "-o", "command=", "-p", str(pid)],
            capture_output=True,
            text=True,
            timeout=10,
            stdin=subprocess.DEVNULL,
        )
    except (subprocess.TimeoutExpired, OSError):
        # Can't confirm identity — assume it is not ours rather than risk
        # signalling a stranger.
        return False
    return result.returncode == 0 and "worker.py" in result.stdout


def _pid_alive(pid: int | None) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        # Exists but owned by another user — so definitely not our worker.
        return False
    return _is_our_worker(pid)


def read_job(job_id: str, reconcile_state: bool = True) -> dict | None:
    path = job_path(job_id)
    if not path.exists():
        return None
    try:
        record = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    if reconcile_state:
        record = reconcile(record)
    return record


def reconcile(record: dict) -> dict:
    """Settle an active record whose worker can no longer finish it.

    A worker writes its own terminal record on a clean exit, so this only fires
    when something went wrong. Three cases, none of which resolve themselves:

    - `running` with a dead worker — killed, crashed, or the machine rebooted.
      Cancelled if the sentinel says so, otherwise failed.
    - `queued` with no pid past the launch grace period — the worker never
      started, and nothing will ever publish a pid. Such records are skipped by
      the liveness path above and spared by prune(), so without this they live
      forever.
    - Cancelled while still queued — settles straight to `cancelled`.
    """
    if record.get("status") not in ACTIVE_STATUSES:
        return record
    if _pid_alive(record.get("worker_pid")):
        return record

    if record.get("status") == "queued" and record.get("worker_pid") is None:
        # Normally just means the worker has not published its pid yet. But if
        # the launch itself failed, nothing will ever publish one — and a
        # pid-less queued record is skipped here and spared by prune(), so it
        # would linger forever. Past the grace period, call it failed.
        age = time.time() - record.get("created_at", 0)
        if age < _LAUNCH_GRACE_SECONDS and not is_cancel_requested(record["id"]):
            return record
        if not is_cancel_requested(record["id"]):
            record["status"] = "failed"
            record["phase"] = "failed"
            record["error"] = (
                f"Worker never started (no pid recorded within "
                f"{_LAUNCH_GRACE_SECONDS}s). Check that python3 can run "
                f"worker.py."
            )
            record["completed_at"] = time.time()
            return write_job(record)

    if is_cancel_requested(record["id"]) or record.get("cancel_requested"):
        record["status"] = "cancelled"
        record["error"] = "Cancelled by request."
    else:
        record["status"] = "failed"
        record["error"] = (
            "Worker exited without recording a result "
            "(killed, crashed, or the machine restarted)."
        )
    record["phase"] = "failed" if record["status"] == "failed" else "cancelled"
    record["completed_at"] = record.get("completed_at") or time.time()
    record["worker_pid"] = None
    return write_job(record)


def list_jobs(limit: int | None = None) -> list[dict]:
    """All jobs, newest first, reconciled."""
    records = []
    for path in jobs_dir().glob("*.json"):
        if path.name.endswith(".schema.json"):
            continue
        try:
            records.append(json.loads(path.read_text()))
        except (json.JSONDecodeError, OSError):
            continue
    records.sort(key=lambda r: r.get("created_at", 0), reverse=True)
    records = [reconcile(r) for r in records]
    return records[:limit] if limit else records


def resolve_job_id(reference: str) -> str:
    """Resolve a full id or unique prefix. Raises on ambiguous/unknown."""
    reference = (reference or "").strip()
    if not reference:
        raise ValueError("No job id given.")

    if is_valid_job_id(reference) and job_path(reference).exists():
        return reference

    # Prefix lookup goes through the enumerated records, never through a path
    # built from caller input — so "../../etc/passwd" simply matches nothing
    # instead of resolving outside the jobs directory.
    matches = [
        r["id"] for r in list_jobs() if r.get("id", "").startswith(reference)
    ]
    if not matches:
        raise ValueError(f"No job matching '{reference}'.")
    if len(matches) > 1:
        raise ValueError(
            f"'{reference}' is ambiguous — matches {len(matches)} jobs: "
            f"{', '.join(matches[:5])}"
        )
    return matches[0]


def latest_job(job_class: str | None = None) -> dict | None:
    for record in list_jobs():
        if job_class is None or record.get("job_class") == job_class:
            return record
    return None


def prune(max_jobs: int | None = None) -> int:
    """Delete the oldest job records beyond the cap. Returns count removed."""
    cap = max_jobs if max_jobs is not None else Config.MAX_JOBS
    records = list_jobs()
    stale = [r for r in records[cap:] if r.get("status") in TERMINAL_STATUSES]
    for record in stale:
        for path in sidecar_paths(record["id"]):
            path.unlink(missing_ok=True)
    return len(stale)


def create_job(job_class: str, request: dict) -> dict:
    """Create a queued job record. The worker rehydrates `request`."""
    job_id = new_job_id(job_class)
    record = {
        "id": job_id,
        "job_class": job_class,
        "status": "queued",
        "phase": "starting",
        "request": request,
        "project_dir": request.get("project_dir"),
        "model": request.get("model"),
        "effort": request.get("effort"),
        "sandbox": request.get("sandbox"),
        "thread_id": None,
        "worker_pid": None,
        "cancel_requested": False,
        "created_at": time.time(),
        "started_at": None,
        "completed_at": None,
        "output": None,
        "structured_output": None,
        "error": None,
        "usage": None,
        "verification": None,
    }
    write_job(record)
    prune()
    return record


def terminate_tree(pid: int) -> None:
    """Kill a worker and the codex process it spawned.

    The worker starts its own process group (start_new_session), so signalling
    the group reaches codex and any shells it spawned. Without this, killing
    only the worker would orphan a codex run that keeps burning quota.
    """
    if not pid:
        return
    # Never signal a pid we cannot confirm is ours: after PID reuse this would
    # kill an unrelated process group.
    if not _is_our_worker(pid):
        return
    try:
        os.killpg(os.getpgid(pid), signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        try:
            os.kill(pid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError):
            pass
